data:
    dataset_path: 'rahular/simple-wikipedia'
    dataset_name: 'default'
    block_size: 256

model:
    vocab_size: 50257 # gpt2 vocab
    context_length: 256
    emb_dim: 384
    n_heads: 2
    n_layers: 2
    dropout_rate: 0.1
    qkv_bias: False
    mlp_bias: True

training:
    num_epochs: 20
    batch_size: 32
    log_interval: 10
    eval_iters: 10
    eval_interval: 50
    save_interval: 200

system:
    device: cpu
