data:
    dataset_path: 'HuggingFaceFW/fineweb-edu'
    dataset_name: 'sample-10BT'
    block_size: 1024

model:
    vocab_size: 50257 # gpt2 vocab

training:
    batch_size: 16 
    log_interval: 200
    eval_iters: 20
    eval_interval: 500

system:
    device: cuda 
