data:
    dataset_path: 'rahular/simple-wikipedia'
    dataset_name: 'default'
    block_size: 256 

model:
    vocab_size: 50257 # gpt2 vocab
    context_length: 64
    emb_dim: 64
    n_heads:  2
    n_layers: 2
    dropout_rate: 0.1
    qkv_bias: False
    mlp_bias: True
    
training:
    batch_size: 2
    log_interval: 10
    eval_iters: 10
    eval_interval: 50
    wandb_log: False 
    max_steps: 100

system:
    device: cpu
